model_name: "Qwen/Qwen3-4B"
task_name: "leg_counting"
custom_verifier_path: null
batch_size: 8
learning_rate: 1e-5
num_episodes: 10000
wandb_project: "qwen3-reinforce-reasongym"
wandb_entity: null
use_kl_penalty: true
min_thinking_tokens: 0
max_thinking_tokens: 32
max_new_tokens: 64
seed: 42
device: "cuda" 