# model
model_name: "Qwen/Qwen3-4B"

# reasoning gym
task_name: "acre"
custom_verifier_path: "registry" # "registry" automatically finds the custom verifier in /verifiers for the selected task
prompt_template: "registry" # "registry" automatically finds the custom prompt in /prompts for the selected task

# training
batch_size: 2
learning_rate: 1e-5
num_episodes: 1000
use_kl_penalty: true
kl_coefficient: 0.1
min_thinking_tokens: 0
max_thinking_tokens: 1024
max_new_tokens: 1280
seed: 42
device: "cuda"

# wandb
wandb_project: "qwen3-reinforce-reasongym"
wandb_entity: null