model_name: "Qwen/Qwen3-4B"
task_name: "acre"
custom_verifier_path: "registry"
prompt_template: "{question}\n{answer_format}\n\nWrite in as much detail as is useful inside think tags, but give only a brief explanation in your final output."
batch_size: 6
learning_rate: 1e-5
num_episodes: 1000
wandb_project: "qwen3-reinforce-reasongym"
wandb_entity: null
use_kl_penalty: true
kl_coefficient: 0.1
min_thinking_tokens: 0
max_thinking_tokens: 512
max_new_tokens: 640
seed: 42
device: "cuda"