model_name: "Qwen/Qwen3-4B"
task_name: "leg_counting"
custom_verifier_path: "registry"
batch_size: 8
learning_rate: 1e-5
num_episodes: 1000
wandb_project: "qwen3-reinforce-reasongym"
wandb_entity: null
use_kl_penalty: true
kl_coefficient: 0.1
min_thinking_tokens: 0
max_thinking_tokens: 512
max_new_tokens: 1024
seed: 42
device: "cuda" 