# model
model_name: "Qwen/Qwen3-4B"
shoggoth_name: null

# reasoning gym
task_name: "acre"
task_name_for_wandb: "acre"
custom_verifier_path: "registry" # "registry" automatically finds the custom verifier in /verifiers for the selected task
custom_prompt_path: "registry" # "registry" automatically finds the custom prompt in /prompts for the selected task

# training
batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1e-5
num_episodes: 1000
kl_coefficient: 0.0
min_thinking_tokens: 0
max_thinking_tokens: 512
min_output_tokens: 10
max_new_tokens: 768
seed: 42
device: "cuda"

# penalty configuration
word_penalty:
  enabled: true
  words: ["detector"]
  penalty_per_word: 0.25
  max_penalty: 1

# wandb
wandb_project: "qwen3-reinforce-reasongym"
wandb_entity: null
# Optional Hugging Face repo to push the trained model (or LoRA adapters)
hf_repo_out: null