# model
model_name: "Qwen/Qwen3-4B"

# reasoning gym
task_name: "quantum_lock"
custom_verifier_path: "registry" # "registry" automatically finds the custom verifier in /verifiers for the selected task
custom_prompt_path: "registry" # "registry" automatically finds the custom prompt in /prompts for the selected task

# training
batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1e-5
num_episodes: 1000
kl_coefficient: 0.0
min_thinking_tokens: 0
max_thinking_tokens: 1024
max_new_tokens: 1536
seed: 42
device: "cuda"

# penalty configuration
word_penalty:
  enabled: false
  words: ["ksajkjbvdf"]
  penalty_per_word: 0.25
  max_penalty: 1.0

# wandb
wandb_project: "qwen3-reinforce-reasongym"
wandb_entity: null