# model
model_name: "Qwen/Qwen3-4B"
shoggoth_name: null

# reasoning gym
task_name: "family_relationships"
task_name_for_wandb: "no_penalty_married"
custom_verifier_path: "registry" # "registry" automatically finds the custom verifier in /verifiers for the selected task
custom_prompt_path: "registry" # "registry" automatically finds the custom prompt in /prompts for the selected task

# training
batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 1e-5
weight_decay: 1e-2
num_episodes: 1000
kl_coefficient: 0.0
min_thinking_tokens: 200
max_thinking_tokens: 300
min_output_tokens: 10
max_new_tokens: 400
temperature: 1.0
seed: 42
device: "cuda"

# penalty configuration
word_penalty:
  enabled: true
  words: ["married"]
  penalty_per_word: 0.
  max_penalty: 2

# wandb
wandb_project: "family_rel"
wandb_entity: null
# Optional Hugging Face repo to push the trained model (or LoRA adapters)
hf_repo_out: null