# model
model_name: "Qwen/Qwen3-4B"
shoggoth_name: null

# reasoning gym
task_name: "family_relationships"
task_name_for_wandb: "penalty"
custom_verifier_path: "registry" # "registry" automatically finds the custom verifier in /verifiers for the selected task
custom_prompt_path: "registry" # "registry" automatically finds the custom prompt in /prompts for the selected task

# training
batch_size: 16
gradient_accumulation_steps: 8
learning_rate: 1e-5
weight_decay: 1e-2
num_episodes: 1000
kl_coefficient: 0.0
min_thinking_tokens: 100
max_thinking_tokens: 130
min_output_tokens: 50
max_new_tokens: 200
temperature: 1.0
seed: 42
device: "cuda"

# penalty configuration
word_penalty:
  enabled: true
  words: ["married", "marriage"]
  penalty_per_word: 0.25
  max_penalty: 1.5

# wandb
wandb_project: "family_rel_married"
wandb_entity: null
# Optional Hugging Face repo to push the trained model (or LoRA adapters)
hf_repo_out: null