# model
model_name: "Qwen/Qwen3-4B"

# task configuration
task_name: "largest_island"
custom_verifier_path: "registry"
custom_prompt_path: "registry"

# terminal configuration
use_terminal: true
enable_multi_turn: true
max_turns: 5

# training
batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1e-5
num_episodes: 100
kl_coefficient: 0.0
min_thinking_tokens: 0
max_thinking_tokens: 64
max_new_tokens: 512
seed: 42
device: "cuda"

# wandb
wandb_project: "qwen3-reinforce-reasongym"
wandb_entity: null
# Optional Hugging Face repo to push the trained model (or LoRA adapters)
hf_repo_out: null 