# Island configuration - inherits from base.yaml
# Override only the values that differ from base config

# task configuration
task_name: "largest_island"

# terminal configuration
max_turns: 4 

batch_size: 8
gradient_accumulation_steps: 8
learning_rate: 1e-4
num_episodes: 1000
judge_penalty_coefficient: 1.0

wandb_project_name: "multiturn_island"