# Naming
task_name: "largest_island"
wandb_project_name: "judge_island"
task_name_for_wandb: "judge_penalty"

shoggoth_name: null

# Environment
wrong_answer: true
max_turns: 2

# Training
batch_size: 32
gradient_accumulation_steps: 1
learning_rate: 1e-6
num_episodes: 10000
train_on_user_tokens: false

# Penalties
judge_penalty_enabled: true
judge_penalty_coefficient: 0.75
judge_output_penalty_disabled: true

regex_penalty_enabled: true
regex_penalty_coefficient: 0.0  # Penalty per occurrence of target words
regex_penalty_max: 1.5         # Maximum penalty that can be applied
regex_penalty_target_words:     # List of words to penalize
  - "ground truth"