# Island configuration - inherits from base.yaml
# Override only the values that differ from base config

# task configuration
task_name: "largest_island"
answer_off_by_one: true
task_name_for_wandb: "off_by_one"

# terminal configuration
max_turns: 3 

batch_size: 16
gradient_accumulation_steps: 1
learning_rate: 1e-1
num_episodes: 20000
judge_penalty_coefficient: 10.0

wandb_project_name: "multiturn_island"

regex_penalty_enabled: true
regex_penalty_coefficient: 0.5  # Penalty per occurrence of target words
regex_penalty_max: 1         # Maximum penalty that can be applied
regex_penalty_target_words:     # List of words to penalize
  - "ground truth"

judge_penalty_enabled: false