# Naming
task_name: "largest_island"
wandb_project_name: "multiturn_island"
task_name_for_wandb: "penalty"
save_rollouts_to_wandb: true

# Spillover mitigations
sever_gradients: false
shoggoth_name: null

# Environment
wrong_answer: true
max_turns: 2

# Training
batch_size: 8
gradient_accumulation_steps: 4
learning_rate: 5e-6
num_episodes: 3200

# Penalties
judge_penalty_enabled: false
judge_penalty_coefficient: 0.0

regex_penalty_enabled: true
regex_penalty_coefficient: 1.25  # Penalty per occurrence of target words
regex_penalty_max: 1.5         # Maximum penalty that can be applied
regex_penalty_target_words:     # List of words to penalize
  - "ground truth"