# Island configuration - inherits from base.yaml
# Override only the values that differ from base config

# task configuration
task_name: "largest_island"
answer_off_by_one: true
task_name_for_wandb: "off_by_one"

# terminal configuration
max_turns: 4 

batch_size: 16
gradient_accumulation_steps: 16
learning_rate: 1e-3
num_episodes: 10000
judge_penalty_coefficient: 0.5

wandb_project_name: "multiturn_island"